USE [master]
GO

/****** Object:  Database [NelsonYoussif]    Script Date: 08/07/2018 20:11:03 ******/
CREATE DATABASE [NelsonYoussif] ON  PRIMARY 
( NAME = N'NelsonYoussif', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\NelsonYoussif.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NelsonYoussif_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\NelsonYoussif_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NelsonYoussif] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NelsonYoussif].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NelsonYoussif] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NelsonYoussif] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NelsonYoussif] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NelsonYoussif] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NelsonYoussif] SET ARITHABORT OFF 
GO

ALTER DATABASE [NelsonYoussif] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NelsonYoussif] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [NelsonYoussif] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NelsonYoussif] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NelsonYoussif] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NelsonYoussif] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NelsonYoussif] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NelsonYoussif] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NelsonYoussif] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NelsonYoussif] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NelsonYoussif] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NelsonYoussif] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NelsonYoussif] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NelsonYoussif] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NelsonYoussif] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NelsonYoussif] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NelsonYoussif] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NelsonYoussif] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NelsonYoussif] SET  READ_WRITE 
GO

ALTER DATABASE [NelsonYoussif] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NelsonYoussif] SET  MULTI_USER 
GO

ALTER DATABASE [NelsonYoussif] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NelsonYoussif] SET DB_CHAINING OFF 
GO

